### ISSUE TITLE
Nice reddit post. Quick suggestion!

### ISSUE THREAD

**Issue by outofgamut** [TowhidKashem/snapchat-clone#1]
At night, in a darker environment (like my living room), it would be helpful if the background color for the app on desktop was something like #cfcfcf instead of #222222, so that the camera gets more backlight provided from the user's monitor.

**Comment by TowhidKashem** [comment]
I understand your point about shining more back light but I think aesthetically it just doesn't look very good. So I'll keep the color dark as is for now, but thank you for the suggestion!
