### ISSUE TITLE
Update Jeeliz FaceFilter

### ISSUE THREAD

**Issue by xavierjs** [TowhidKashem/snapchat-clone#3]
Hi,

I have pushed some major bugfixes on Jeeliz FaceFilter ( https://github.com/jeeliz/jeelizFaceFilter ) these last weeks.
There are some important compatibility improvements (related to https://github.com/jeeliz/jeelizFaceFilter/issues/186 )
it would be worth updating :)

Best,
Xavier

**Comment by TowhidKashem** [comment]
Hey @xavierjs sorry for the late reply!

Ok so I thought this would be a simple update, I pulled the latest but doing so broke all the filters that I had pulled and modified from the demos. I guess there are some breaking changes there. I don't have the time to go through and update those right now so I think I'll skip the update for now.

**Comment by TowhidKashem** [comment]
@xavierjs I updated the lib to the latest (commit hash 06afda0ea88a0fe30ff43d586c89024795747caa). This time didn't encounter any issues with prior scripts breaking!
